# Generated by Django 6.0.2 on 2026-03-01 01:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('eligibility_notes', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('civil_status', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Widowed', 'Widowed')], max_length=20)),
                ('year_level', models.PositiveIntegerField()),
                ('gwa_percentage', models.FloatField()),
                ('gwa_numeric_1to5', models.FloatField()),
                ('course', models.CharField(max_length=200)),
                ('course_category', models.CharField(choices=[('Agriculture', 'Agriculture'), ('Business', 'Business'), ('Coconut-Related', 'Coconut-Related'), ('Education', 'Education'), ('Engineering', 'Engineering'), ('Health Sciences', 'Health Sciences'), ('Hospitality', 'Hospitality'), ('IT/Computing', 'IT/Computing'), ('Science', 'Science'), ('Social Sciences', 'Social Sciences'), ('Sugarcane-Related', 'Sugarcane-Related'), ('Other', 'Other')], max_length=50)),
                ('shs_strand', models.CharField(choices=[('STEM', 'STEM'), ('ABM', 'ABM'), ('HUMSS/GAS', 'HUMSS/GAS'), ('TVL', 'TVL'), ('TVL/ABM', 'TVL/ABM'), ('Other', 'Other')], max_length=20)),
                ('enrolled_hei_type', models.CharField(choices=[('SUC', 'SUC'), ('LUC', 'LUC'), ('Private HEI', 'Private HEI')], max_length=20)),
                ('region', models.CharField(choices=[('NCR', 'NCR'), ('CAR', 'CAR'), ('Region I', 'Region I'), ('Region II', 'Region II'), ('Region III', 'Region III'), ('Region IV-A', 'Region IV-A'), ('Region IV-B', 'Region IV-B'), ('Region V', 'Region V'), ('Region VI', 'Region VI'), ('Region VII', 'Region VII'), ('Region VIII', 'Region VIII'), ('Region IX', 'Region IX'), ('Region X', 'Region X'), ('Region XI', 'Region XI'), ('Region XII', 'Region XII'), ('Region XIII', 'Region XIII'), ('BARMM', 'BARMM'), ('CARAGA', 'CARAGA')], max_length=50)),
                ('barangay_type', models.CharField(choices=[('Urban', 'Urban'), ('Rural', 'Rural')], max_length=10)),
                ('family_annual_income_php', models.FloatField()),
                ('family_size', models.PositiveIntegerField()),
                ('parents_occupation', models.CharField(max_length=200)),
                ('is_solo_parent_dependent', models.BooleanField(default=False)),
                ('is_pwd', models.BooleanField(default=False)),
                ('is_indigenous_people', models.BooleanField(default=False)),
                ('is_4ps_beneficiary', models.BooleanField(default=False)),
                ('is_ofw_dependent', models.BooleanField(default=False)),
                ('has_existing_scholarship', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveIntegerField()),
                ('confidence_score', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scholarship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='scholarships.scholarship')),
                ('student_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='scholarships.studentprofile')),
            ],
            options={
                'ordering': ['student_profile', 'rank'],
                'unique_together': {('student_profile', 'rank')},
            },
        ),
    ]
