# Generated by Django 6.0.2 on 2026-03-01 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='income_range',
            field=models.CharField(choices=[('10000-19999', '₱10,000 - ₱19,999'), ('20000-29999', '₱20,000 - ₱29,999'), ('30000-39999', '₱30,000 - ₱39,999'), ('40000-49999', '₱40,000 - ₱49,999'), ('50000-59999', '₱50,000 - ₱59,999'), ('60000-69999', '₱60,000 - ₱69,999'), ('70000-79999', '₱70,000 - ₱79,999'), ('80000-89999', '₱80,000 - ₱89,999'), ('90000-100000', '₱90,000 - ₱100,000')], default='10000-19999', max_length=20),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='barangay_type',
            field=models.CharField(blank=True, default='Rural', max_length=10),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='enrolled_hei_type',
            field=models.CharField(blank=True, default='SUC', max_length=20),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='family_size',
            field=models.PositiveIntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='region',
            field=models.CharField(blank=True, default='Region II', max_length=50),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='shs_strand',
            field=models.CharField(blank=True, default='STEM', max_length=20),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='year_level',
            field=models.PositiveIntegerField(choices=[(1, '1st Year'), (2, '2nd Year'), (3, '3rd Year'), (4, '4th Year'), (5, '5th Year')]),
        ),
    ]
