# Generated by Django 6.0.2 on 2026-04-05 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0002_studentprofile_income_range_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='match_reasons',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='application_period',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='application_steps',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='benefits',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='provider',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='requirements',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='website',
            field=models.URLField(blank=True, default=''),
        ),
    ]
